# Generated by Django 4.2.2 on 2023-07-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_handling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingworkshop',
            name='author_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='trendingworkshop',
            name='author_photo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
