# Generated by Django 4.2.2 on 2023-07-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_handling', '0003_rename_price_trendingworkshop_new_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trendingWorkshop',
            new_name='allWorkshop',
        ),
        migrations.DeleteModel(
            name='popularWorkshop',
        ),
    ]
