# Generated by Django 4.2.2 on 2023-07-01 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_handling', '0005_author_remove_allworkshop_author_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_handling.allworkshop')),
            ],
        ),
    ]
