# Generated by Django 4.2.2 on 2023-07-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_handling', '0008_websitelogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='workshopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='websiteLogo',
        ),
        migrations.AddField(
            model_name='allworkshop',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='page_handling.workshopcategory'),
            preserve_default=False,
        ),
    ]
