# Generated by Django 4.2.2 on 2023-07-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_handling', '0009_workshopcategory_delete_websitelogo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.TextField(max_length=500)),
                ('our_goal', models.TextField(max_length=150)),
                ('about_short_description', models.TextField(max_length=500)),
                ('about_title', models.TextField(max_length=200)),
                ('about_long_description', models.TextField(max_length=1500)),
                ('bullet_point_1', models.TextField(max_length=100)),
                ('bullet_point_2', models.TextField(max_length=100)),
                ('bullet_point_3', models.TextField(max_length=100)),
                ('bullet_point_4', models.TextField(max_length=100)),
                ('about_image_1', models.ImageField(upload_to='uploads/')),
                ('about_image_2', models.ImageField(upload_to='uploads/')),
                ('about_image_3', models.ImageField(upload_to='uploads/')),
                ('about_image_4', models.ImageField(upload_to='uploads/')),
                ('author_image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Clientele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='uploads/')),
                ('image_2', models.ImageField(upload_to='uploads/')),
                ('image_3', models.ImageField(upload_to='uploads/')),
                ('image_4', models.ImageField(upload_to='uploads/')),
                ('image_5', models.ImageField(upload_to='uploads/')),
                ('image_6', models.ImageField(upload_to='uploads/')),
                ('image_7', models.ImageField(upload_to='uploads/')),
                ('image_8', models.ImageField(upload_to='uploads/')),
                ('image_9', models.ImageField(upload_to='uploads/')),
                ('image_10', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=500)),
                ('photo', models.ImageField(upload_to='uploads/')),
                ('display', models.BooleanField(default=False)),
            ],
        ),
    ]
