# Generated by Django 4.2.2 on 2023-07-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_handling', '0015_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, default='uploads/default_photo.jpg', null=True, upload_to='uploads/'),
        ),
    ]
