# Generated by Django 4.1.1 on 2023-07-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_handling', '0018_adbanner_clienteleimage_promobanner_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=250)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blog/images')),
                ('user_name', models.TextField(max_length=150)),
                ('user_photo', models.ImageField(blank=True, upload_to='blog/images')),
                ('is_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('contact_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Clientele',
        ),
    ]
