# Generated by Django 4.2.2 on 2023-06-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loginContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.TextField()),
                ('secondary_title', models.TextField()),
                ('student_stats', models.CharField(max_length=200)),
                ('main_image', models.ImageField(upload_to='')),
                ('user_img_1', models.ImageField(upload_to='')),
                ('user_img_2', models.ImageField(upload_to='')),
                ('user_img_3', models.ImageField(upload_to='')),
                ('user_img_4', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='registerContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.TextField()),
                ('secondary_title', models.TextField()),
                ('student_stats', models.CharField(max_length=200)),
                ('main_image', models.ImageField(upload_to='')),
                ('user_img_1', models.ImageField(upload_to='')),
                ('user_img_2', models.ImageField(upload_to='')),
                ('user_img_3', models.ImageField(upload_to='')),
                ('user_img_4', models.ImageField(upload_to='')),
            ],
        ),
    ]
