# Generated by Django 4.2.2 on 2023-06-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logincontent',
            old_name='user_img_1',
            new_name='avatar_img_1',
        ),
        migrations.RenameField(
            model_name='logincontent',
            old_name='user_img_2',
            new_name='avatar_img_2',
        ),
        migrations.RenameField(
            model_name='logincontent',
            old_name='user_img_3',
            new_name='avatar_img_3',
        ),
        migrations.RenameField(
            model_name='logincontent',
            old_name='user_img_4',
            new_name='avatar_img_4',
        ),
        migrations.RenameField(
            model_name='registercontent',
            old_name='user_img_1',
            new_name='avatar_img_1',
        ),
        migrations.RenameField(
            model_name='registercontent',
            old_name='user_img_2',
            new_name='avatar_img_2',
        ),
        migrations.RenameField(
            model_name='registercontent',
            old_name='user_img_3',
            new_name='avatar_img_3',
        ),
        migrations.RenameField(
            model_name='registercontent',
            old_name='user_img_4',
            new_name='avatar_img_4',
        ),
    ]
